name: Sync To Gitee
on: page_build
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Mirror
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/Slowlyo
          dst: gitee/Slowlyo
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          static_list: "owl-admin-doc"
#        uses: wearerequired/git-mirror-action@master
#        env:
#          SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
#        with:
#          source-repo: "git@github.com:Slowlyo/owl-admin-doc.git"
#          destination-repo: "git@gitee.com:Slowlyo/owl-admin-doc.git"
      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
          # 注意替换为你的 Gitee 用户名
          gitee-username: ${{ secrets.GITEE_USERNAME }}
          # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          # 注意替换为你的 Gitee 仓库，仓库名严格区分大小写，请准确填写，否则会出错
          gitee-repo: slowlyo/owl-admin-doc
          # 要部署的分支，默认是 master，若是其他分支，则需要指定（指定的分支必须存在）
          branch: master