name: Sync And Deploy
on:
  workflow_dispatch: { }
  push:
    branches:
      - master
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/configure-pages@v2
      - uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1
      - name: Sync Mirror
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
        with:
          source-repo: "git@github.com:Slowlyo/owl-admin-doc.git"
          destination-repo: "git@gitee.com:Slowlyo/owl-admin-doc.git"